### ISSUE TITLE
Prop value gets truncated 

### ISSUE THREAD

**Issue by McYoloSwagHam** [Magisk-Modules-Repo/MagiskHidePropsConf#101]
`dalvik.vm.dex2oat-flags=--inline-max-code-units=0`

I'm trying to set this prop, but the `=0` at the end always gets truncated and I'm left with `--inline-max-code-units`

**Comment by Didgeridoohan** [comment]
That's an interesting one... I've never seen a prop value with an equal sign in it.

**Comment by McYoloSwagHam** [comment]
Yeah it's a bit weird, so it's understandable

**Comment by Didgeridoohan** [comment]
Fixed in 92f276675689f4ac07a13475380eb9b6fc123454
