### ISSUE TITLE
LineageOS 18.1 doesn't pass CTS Profile Match

### ISSUE THREAD

**Issue by ezxpro** [Magisk-Modules-Repo/MagiskHidePropsConf#105]
My device is a Redmi 7 (onclite) and I always change the fingerprint with MagiskHide Props and it passes Safety Net. Now I'm on lineageOS 18.1 and it doesn't work. I also always pick the same fingerprint for Android 11 ROMs and this is the first time CTS Profile Match fails while using this fingerprint. Here are the logs collected from MagiskhideProps
[propslogs.tar.gz](https://github.com/Magisk-Modules-Repo/MagiskHidePropsConf/files/6764452/propslogs.tar.gz)

**Comment by Didgeridoohan** [comment]
Only thing I can see in the logs is that the print doesn't seem to have been changed. Can't say why though, especially since the Magisk log is completely garbled...

**Comment by ezxpro** [comment]
Well, in the meantime i found out (via your documentation, i think) that there's a that there's a magisk module named "Universal Safety Net Fix 1.2.0" by kdrag0n, which fixes the issue.

Now, I'm not sure if what I'm saying here is bullshit, but from what I could gather from talking to folks in the official LineageOS telegram , it seems this is intentional. I can't confi that but it sure is the only ROM i ever installed in this device where your module didn't work out of the box.

**Comment by Didgeridoohan** [comment]
Other ROMs you've tried probably have that fix integrated. Official LOS never includes anything to circumvent SafetyNet.
