### ISSUE TITLE
Fingerprint submission for ASUS Zenfone 8

### ISSUE THREAD

**Issue by spacedingo** [Magisk-Modules-Repo/MagiskHidePropsConf#108]
_AIDA64 for Android v1.78 Report_

Manufacturer: asus
Model: ASUS_I006D
Brand: asus
Board: lahaina
Device: ASUS_I006D
Hardware: qcom
Platform: lahaina
Product: EU_I006D
Installed RAM: 8 GB

Android Version: 11
API Level: 30
Android Security Patch Level: 2021-05-05
Rooted Device: Yes
Baseband: M3.13.24.39-Sake_0000110,M3.13.24.39-Sake_0000110
Build ID: RKQ1.201022.002.30.11.51.83 release-keys
Codename: REL
Fingerprint: asus/EU_I006D/ASUS_I006D:11/RKQ1.201022.002/30.11.51.83:user/release-keys
ID: RKQ1.201022.002
Incremental: 30.11.51.83

---------
Thank you!

**Comment by Didgeridoohan** [comment]
Thank you. Added in d1ee313ac379002a6e46b81fee3d35e7f12e57c8
