### ISSUE TITLE
Added another FP

### ISSUE THREAD

**Issue by gloeyisk** [Magisk-Modules-Repo/MagiskHidePropsConf#11]
Is it possible to add Redmi 3/3 Pro [ido] fingerprint?
You can take a look first. Thanks.
https://github.com/gloeyisk/BuildFPChanger

**Comment by Didgeridoohan** [comment]
I'll add it to the waiting list and I'll check it out when I have an opportunity. If it passes CTS I'll definitely add it to the module.

**Comment by gloeyisk** [comment]
> I'll add it to the waiting list and I'll check it out when I have an opportunity. If it passes CTS I'll definitely add it to the module.

It's passes. I'm already do personal testing which for my current device (Redmi 3) the CTS is false while using any GSI ROMs. With applied my personal FP, it's passed.
Btw thanks for your time.

**Comment by Didgeridoohan** [comment]
Added to the module list.
