### ISSUE TITLE
Use wget to check network connection instead of ping

### ISSUE THREAD

**Issue by ysc3839** [Magisk-Modules-Repo/MagiskHidePropsConf#111]
Because google.com is not accessible in China, it will always think it's no network. Replace the ping with wget raw.githubusercontent.com could solve the issue.
https://github.com/Magisk-Modules-Repo/MagiskHidePropsConf/blob/d1ee313ac379002a6e46b81fee3d35e7f12e57c8/common/util_functions.sh#L885-L895

**Comment by Didgeridoohan** [comment]
Interesting...

And that definitely sounds like a viable solution, I'll check it out.

**Comment by Didgeridoohan** [comment]
Fixed in 92f276675689f4ac07a13475380eb9b6fc123454
