### ISSUE TITLE
Magisk hide module problem

### ISSUE THREAD

**Issue by Neeru98** [Magisk-Modules-Repo/MagiskHidePropsConf#114]
I am using magisk Alpha which doesnt have magisk hide features but it has zygisk which has denylist so i deny all permission for root to gms ,and the basic intregity passed but when i install the magisk hide props configure module ,basic intregity failed.

**Comment by Didgeridoohan** [comment]
Magisk Alpha is experimental at best and I've not looked any closer at it yet. I'm likely wait until John releases the next Canary before testing stuff closer.

But, there has been reports of the latest Alpha builds causing problems with SafetyNet, so it might be an issue with the new code.

If you could post them, it would be interesting to see the module logs though.
https://github.com/Magisk-Modules-Repo/MagiskHide-Props-Config/blob/master/README.md#logs
