### ISSUE TITLE
Regarding Magisk's upcoming updates

### ISSUE THREAD

**Issue by justkamiii** [Magisk-Modules-Repo/MagiskHidePropsConf#121]
As everyone can see from the new Magisk Canary releases, there's quite a lot of improvements/changes for the next major Magisk update, and one of these changes is the complete removal of MagiskHide, an essential component of MagiskHide Props Config. If you try to use MHPC in Canary, it just won't work/bypass things like SafetyNet. Are there any plans on updating this module once the updates rolls out to everyone? Is there already plans under the hood to possibly fix this? Will the whole project just become useless? I would be glad to hear about this, and I also think that it's something important for everyone else to know as well.
Kind regards, Kamiii

**Comment by Didgeridoohan** [comment]
The current release of MagiskHide Props Config works perfectly fine with the current Magisk Canary builds (23012 as of writing this).

Not much has changed really...

If you have a device that isn't certified (usually custom ROM) you can apply a certified fingerprint, as usual. If you have a modern device that uses hardware backed key attestation you will need to use the Universal SafetyNet Fix, as usual. The only accommodation that has been done on the module side of things is to add all the prop changes that MagiskHide used to do. Those are found under "Edit MagiskHide props". Universal SafetyNet Fix does the same thing. If you're not using USNF you'll also need to set up the Magisk Deny list and add the gms and unstable processes of Play Services.

That should be it and I have SafetyNet passing without issue using this module on build 23012...

Once the next stable Magisk release draws closer I'll update the docs to better reflect these minor changes.

**Comment by justkamiii** [comment]
Huh, interesting. Something might have been screwed for some reason for it t

**Comment by justkamiii** [comment]
Interesting, thanks for the clarification. 
Looking at the SafetyNet issue, that's strange. I had a Custom A7 ROM in my old device which passed SN. I ended up having to reinstall the Stock ROM because of some issues with the device, and now suddenly w/ me trying out Magisk Canary and reinstalling MHPC, I assumed that it wasn't working because of the MagiskHide removal. It made sense for me at 1 AM lol.
Once again, thanks for clarifying this.
