### ISSUE TITLE
sorry if in wrong spot - but can this make a 3xl look like an xl?

### ISSUE THREAD

**Issue by pointbob** [Magisk-Modules-Repo/MagiskHidePropsConf#124]
sorry if in wrong spot - but can this make a 3xl look like an xl? i'd like to spoof my 3xl into appearing as an xl thx

**Comment by Didgeridoohan** [comment]
You can always try the device simulation feature.

If that's not enough you can try changing more props with the "Add/edit custom props" feature. "But which ones should I change", you ask.You'd have to do that research yourself, I have no idea...
