### ISSUE TITLE
Doesnt work unfortunately on magisk 24.1

### ISSUE THREAD

**Issue by Relected** [Magisk-Modules-Repo/MagiskHidePropsConf#135]
Since the removal of magiakhide and the introduction to zygisk, this module doesn't work anymore and devices with the latest version of Magisk won't pass safetynet, isnit possible for this module to work with zygisk for passing safetynet CTS profiles on gsi Roms and/or unlocked botloaders?

**Comment by lss4** [comment]
> Since the removal of magiakhide and the introduction to zygisk, this module doesn't work anymore and devices with the latest version of Magisk won't pass safetynet, isnit possible for this module to work with zygisk for passing safetynet CTS profiles on gsi Roms and/or unlocked botloaders?

You need to know that Zygisk by itself does not conceal anything (not even itself). Shamiko is needed to conceal root and other traces from now on. When using Shamiko, Enforce DenyList must be turned off.

However, while Shamiko can sufficiently conceal other sensitive traces, Momo can still report the device is "running a custom ROM", and it appears to have picked up both the spoofed and original fingerprints.

I don't care about Safety Net as I'm using microG with NanoDroid, but Momo can be considered a more in-depth system integrity check.

**Comment by Didgeridoohan** [comment]
As noted above, you'll likely need more tools than just this module to pass SafetyNet.

**Comment by Relected** [comment]
> As noted above, you'll likely need more tools than just this module to pass SafetyNet.
but i already have universal safetynet fix and shamiko and enforce deny list disabled and i still get CTS profile doesnt match, i tried all possible settings for this and it doesnt work

**Comment by lss4** [comment]
> > enforce deny list disabled
> 
> What happens if you enable it?

Shamiko will NOT work as Zygisk stuffs won't be activated for apps in the denylist, if enforced.

**Comment by Didgeridoohan** [comment]
@Relected If you've got problems getting this module to work you'll need to make a proper bug report with logs. Just saying "the module does nothing anymore" means nothing if you can't show it.

**Comment by Relected** [comment]
@Didgeridoohan I just created a new issue about that with logs, I hope it gets resolved soon
