### ISSUE TITLE
Failed cts on note 20 ultra

### ISSUE THREAD

**Issue by daisys77** [Magisk-Modules-Repo/MagiskHidePropsConf#138]
My note 20 ultra is rooted was working fine. Yesterday it stopped working. Root apps say its rooted and some say not rooted. Not sure which one root checker to use. Now
[Help] failing Basic and  Cts profile, evaluation is Basic . I have magisk latest and safteynet for zygist installed. zygist enabled and lsposed installed with google play store and Google services ticked. Magiskhideprop module installed. I am still failing cts. Shamiko module with zygist enforce list disabled. I reinstalled the modules still can't seem to get it to work. Magisk Installed alpha (24201) Zygist yes Ram yes.
![Screenshot_20220306-134232_YASNAC](https://user-images.githubusercontent.com/22896536/156925968-2ec9a03c-c2ab-40a5-b2b1-b565ac042e1e.jpg)
![Screenshot_20220306-132538](https://user-images.githubusercontent.com/22896536/156925971-8bd694df-1ff0-461c-8374-c941e2649f60.jpg)
![Screenshot_20220306-132039_Shell](https://user-images.githubusercontent.com/22896536/156925972-b09a92b7-beee-4dca-bdbb-c6d898998b66.jpg)

**Comment by daisys77** [comment]
![Screenshot_20220306-131844](https://user-images.githubusercontent.com/22896536/156924933-87158a6a-af4c-440b-94f2-1ea11037aca2.jpg)
![Screenshot_20220306-131503](https://user-images.githubusercontent.com/22896536/156924934-8e47a9be-e102-4c34-afdf-c53c6abb6b05.jpg)
![Uploading Screenshot_20220306-075218_YASNAC.jpg…]()

**Comment by Didgeridoohan** [comment]
Since you're failing both Basic integrity and CTS profile it's unlikely to have anything to do with this module.
