### ISSUE TITLE
Unable to edit custom prop values (v.3.0.1)

### ISSUE THREAD

**Issue by BanditGR** [Magisk-Modules-Repo/MagiskHidePropsConf#16]
As title implies, after the latest module update (3.0.1), when attempting to select a custom prop from the props script submenu - option 5 Add/edit custom props - from the main menu, when selecting the number corresponding to the custom prop, the script will fail to move you to the next menu where you can actually edit the value. In fact you won't be able to go back to the main menu either, as the terminal is stuck awaiting input, forcing you to end terminal emulator manually. 

The only workaround so far is to reset all custom props and re-create them one by one via the terminal script (this option works fine) or just make a configuration file.

**Comment by Didgeridoohan** [comment]
Fixed in https://github.com/Magisk-Modules-Repo/MagiskHidePropsConf/commit/f938bc663c514c2c80b5e06fc46e26503d16298d
