### ISSUE TITLE
Forking this Project and need your support

### ISSUE THREAD

**Issue by vithusel** [Magisk-Modules-Repo/MagiskHidePropsConf#160]
It seems like this project has been abandoned.

As Android 13 is just around the corner. I'm going to take over this project so we can continue to develop it.
You can help by sending your devices fingerprints to https://discord.gg/4cGAxXwkca

The forked repo for this project is https://git.vithusel.me/vithusel/MagiskHidePropsConf

It will take a few weeks before I make my first release. But I wont be able to continue Didgeridoohan's hard work without your fingerprint submission's. Focusing mainly on Android 12 & 13. If you have submissions, send a message in the discord Fingerprint channel and ill get it processed!

I mean no disrespect to Didgeridoohan. I saw his post about him saying he was too swamped IRL to work on this back in Feb. Not too sure if hes still in the same circumstances atm but figured i would step in for him till hes back.

**Comment by roses4rashists** [comment]
It's been almost 1 month, I don't see any changes in your repo other than replacing Didgeridoohan's name with your own. 

Also curious is your transition to your own domain name. Neither of these factors drive much trust to your offer to take over as maintainer. Just a heads up.

**Comment by dumblob** [comment]
@vithusel could you allow sign-in into your gitlab instance using gitlab.com credentials? Thanks!

**Comment by vithusel** [comment]
> It's been almost 1 month, I don't see any changes in your repo other than replacing Didgeridoohan's name with your own.
> 
> Also curious is your transition to your own domain name. Neither of these factors drive much trust to your offer to take over as maintainer. Just a heads up.

Hi, 
I've been making changes where i can. There's a few issues when running the module on Android 13 so I'm working on fixing those issues. I've not been pushing any of that to my git as there has been no need so far. 

Regarding moving the repo to my own domain. That's just a case of making my life easier. I have my own gitlab instance for work so it makes sense for me to use my own server. Beta releases have been made available and i have been dealing directly with users to test fixes. 

I believe no further explanation is required. Although the repo is hosted on my own server i've left it public so anyone can view it.

**Comment by vithusel** [comment]
> @vithusel could you allow sign-in into your gitlab instance using gitlab.com (and potentially others like google.com, github.com, etc.) credentials? Thanks!

Hi. I've just enabled account create on my instance as it would be great to have people submit issues directly within the Repo. 
I can have a look at using external authentication but i cannot guarantee i will get that setup soon. I have a lot of different projects nearing completion so i need to prioritise my time on those for the moment.

**Comment by raxod502** [comment]
Note: per announcement at https://discord.com/channels/938429890464710657/1034854478018527262/1069218481620402267, the repository https://git.vithusel.me/vithusel/MagiskHidePropsConf has moved to https://git.vithuselservices.co.uk/vithusel/MagiskHidePropsConf

The latest development fingerprints in this fork appear to be located on a separate branch at https://git.vithuselservices.co.uk/vithusel/MagiskHidePropsConf/-/blob/Experimental/common/prints.sh

At the current time I have been unable to find any support for Android 13 in what's available on GitLab, or a discussion of the current status, although I'd be very interested in such support.
