### ISSUE TITLE
How to list all props of the phone?

### ISSUE THREAD

**Issue by bphd** [Magisk-Modules-Repo/MagiskHidePropsConf#163]

**Comment by crok** [comment]
[`adb shell getprop`](https://adbshell.com/commands/adb-shell-getprop) or basically `getprop`.. doesn't even need root priv., works from a simple terminal as well..

But please use Google/DuckDuckGo/Searx/Qwant/whatever search engine you prefer before opening an issue.

**Comment by bphd** [comment]
Yeah I found it like 15 minutes ago, sorry
