### ISSUE TITLE
S9 9.0.0 fingerprint...

### ISSUE THREAD

**Issue by HTAEDFOLEGNA** [Magisk-Modules-Repo/MagiskHidePropsConf#17]
Is there ever going to be a device fingerprint for s9 on Pie (9.0.0)

**Comment by Didgeridoohan** [comment]
Of course, if you (or anyone) can provide me with one:
https://github.com/Magisk-Modules-Repo/MagiskHidePropsConf/blob/master/README.md#please-add-support-for-device-x
