### ISSUE TITLE
[bug] 3.5.0 and 3.5.1 update in magisk will be wrong (as shown), the keyboard (y / n) option will not pop up.

### ISSUE THREAD

**Issue by 2220209876** [Magisk-Modules-Repo/MagiskHidePropsConf#21]
[bug] 3.5.0 and 3.5.1 update in magisk will be wrong (as shown), the keyboard (y / n) option will not pop up. There will be some problems after restarting the phone, then uninstalling the module and then installing it will work properly (both versions will have this problem when upgrading in magisk)
![Screenshot_Magisk_Manager_20190403-141416](https://user-images.githubusercontent.com/7346652/55560359-a62d4500-5722-11e9-9c81-04eb0d254755.png)

Also in the 3.5.0 version https://github.com/Magisk-Modules-Repo/MagiskHidePropsConf/issues/18 This problem seems to have been solved by you

**Comment by Didgeridoohan** [comment]
Fixed in 69b7ab1367945318b46feafe08be65a2faa9f431
