### ISSUE TITLE
Doesn't install on Pixel 3 with Android 9 and Magisk v19.0

### ISSUE THREAD

**Issue by CaseyBakey** [Magisk-Modules-Repo/MagiskHidePropsConf#23]
Hello there.

I'm trying to install this module directly from Magisk Manager but I'm getting an error:

```
- Copying zip to temp directory
- Installing MagiskHide_Props_Config-v4.0.1-v52.zip
- Current boot slot: _b
- Mounting /system, /vendor
Archive:  /data/user/0/com.unP.nr.NhrNnY.JN/cache/install.zip
  inflating: post-fs-data.sh
  inflating: prints.sh
  inflating: propsconf_conf
  inflating: propsconf_late
  inflating: service.sh
  inflating: util_functions.sh
  inflating: install.sh
  inflating: module.prop
  inflating: uninstall.sh
- Found /data/adb/magisk_merge.img
e2fsck 1.43.3 (04-Sep-2016)
- Mount /data/adb/magisk_merge.img to /dev/magisk_img
*******************************
MagiskHide Props Config v4.0.1
    By Didgeridoohan @XDA
*******************************

! Magisk version not supported!
! Please install Magisk v19+!
! Installation failed
```

Device: Pixel 3 (blueline)
Android version: AOSP 9.0.0 (PQ2A.190405.003)
Magisk version: v19.0 (1900), from releases tab on Magisk GitHub's page

Any idea on this?

**Comment by Didgeridoohan** [comment]
You likely need to reinstall Magisk, by direct install from the Magisk Manager.

If you keep having issues after that I need to see the full installation log (the save log button in the module flashing window) and module logs:
https://github.com/Magisk-Modules-Repo/MagiskHide-Props-Config/blob/master/README.md#logs

**Comment by CaseyBakey** [comment]
I'm in a setup where I can not reinstall Magisk.  
Magisk is embedded in my boot.img, which is signed with my verity key.  
Reinstalling it will trash my secure boot.  

You can see, however that everything is correctly setup:  
![Screenshot_20190411-084009](https://user-images.githubusercontent.com/20017609/55957897-6f30c500-5c35-11e9-8ad7-8d0bcbc26f00.png)


Here is a screenshot of the "bug": 
![Screenshot_20190411-083748](https://user-images.githubusercontent.com/20017609/55957826-3b559f80-5c35-11e9-92fe-1ef1672cd1bf.png)

**Comment by Didgeridoohan** [comment]
That's your issue then... Magisk isn't properly installed.

Screenshots are no good if I'm going to do any kind of analysis. I need the logs.

**Comment by CaseyBakey** [comment]
Ok, here are the files I manage to recover in /data/cache/ by being root within Termux.

[magisk.log](https://github.com/Magisk-Modules-Repo/MagiskHidePropsConf/files/3070152/magisk.log)

[propsconf_install.log](https://github.com/Magisk-Modules-Repo/MagiskHidePropsConf/files/3070154/propsconf_install.log)

I don't see why my Magisk is detected as build 1810?

**Comment by Didgeridoohan** [comment]
When you updated from Magisk v18.1, you didn't do a proper update, resulting in core parts still being on 18100... If you can't do a proper update you'll have to uninstall Magisk and start over.

Closing this since it's not a module issue.

**Comment by CaseyBakey** [comment]
I can confirm this was not module-related.
I was testing crazy stuff (embed Magisk in a ROM I was compiling, to sign it with my own keys, to have root and secure boot).
Using this module right now, and it works fine. Thx and keep up the good work!
