### ISSUE TITLE
How to contribute and and new devices fingerprint?

### ISSUE THREAD

**Issue by AreYouLoco** [Magisk-Modules-Repo/MagiskHidePropsConf#29]
Hi I have extracted build.props of the stock rom for my device. Elephone p9000 it's not on the list (yet?)

Is there list that I can contribute and add a pull-request via github? How?

**Comment by Didgeridoohan** [comment]
https://github.com/Magisk-Modules-Repo/MagiskHidePropsConf/blob/master/common/prints.sh

Or just post in the xda support thread.

**Comment by AreYouLoco** [comment]
Ok thanks I will do that. You could add this info in README.md.

**Comment by AreYouLoco** [comment]
I still have a question. What is the syntax?
This is an example:
Zuk Z2 Pro (7.0)=ZUK/z2_row/z2_row:7.0/NRD90M/2.5.435_170525:user/release-keys
which props I have to get that are separated by slash /?

**Comment by Didgeridoohan** [comment]
That's the full fingerprint. And everything is actually covered in the documentation. I know it's extensive, but it's there... I could probably make it clearer about how to submit a fingerprint though

**Comment by AreYouLoco** [comment]
Read-the-docs rule apply to everything! I have found all the necessary info there.

Tomorrow I will flash stock for a moment to get props and will send a pull request.
Will be happy if you check and merge.
