### ISSUE TITLE
Phone not booting after changing props.

### ISSUE THREAD

**Issue by AreYouLoco** [Magisk-Modules-Repo/MagiskHidePropsConf#30]
Hi I tried to set props to some random device but phone refuses to boot now.

I also tried reset_mhpc in /cache. After that it boots but basic apps like systemui and phone are crashing constantly. And I cannot do anything useful to fix that. I also tried adb shell and running props to reset everything but I cannot su at this stage.

Any ideas how to proceed?

**Comment by AreYouLoco** [comment]
I also tried to disable the module with https://github.com/Pzqqt/Magisk_Manager_Recovery_Tool but still crashes. Damn I forgot to backup stuff...

**Comment by Didgeridoohan** [comment]
The props you set must have changed something in your system. If that persist after a module reset there's nothing I can do. Full reset might be necessary...
