### ISSUE TITLE
Bootloop after enabling device emulation, reset_mhpc doesn't work

### ISSUE THREAD

**Issue by leo60228** [Magisk-Modules-Repo/MagiskHidePropsConf#34]
I've also tried enabling Magisk Core-Only mode, which *does* fix the problem, making me think this is a bug with the module.

**Comment by Didgeridoohan** [comment]
Device simulation has a really high chance if causing all kinds of issues. I believe I've written that in both the terminal ui and the documentation...

If the reset function doesn't work I would need to see the module logs to know what's wrong (it's explained in the docs), but you can also do things manually. Just delete /data/adb/modules/MagiskHidePropsConf/system.prop and /data/adb/mhpc/propsconf_late and everything should be reset.
