### ISSUE TITLE
Seems not compatible with magisk 20

### ISSUE THREAD

**Issue by JiahanChen1** [Magisk-Modules-Repo/MagiskHidePropsConf#36]
Just flashed a new room and magisk, and find magisk has update. Updated to magisk 20 and flash propsconfig and failed. No reason shown. Maybe the only reason is magisk 20?
![Screenshot_20191011-224318](https://user-images.githubusercontent.com/55709909/66693900-f827c800-ec7b-11e9-8461-8ba7f111de2f.jpg)

**Comment by Didgeridoohan** [comment]
Like I wrote in the XDA thread, the install log is what will show what's going on.

**Comment by ovrunq** [comment]
Working with no problem here.

**Comment by Didgeridoohan** [comment]
No response. Closing.
