### ISSUE TITLE
Is there a way to whitelist an app?

### ISSUE THREAD

**Issue by cs-usst** [Magisk-Modules-Repo/MagiskHidePropsConf#43]
I'm using this module because i want to hide my model information from Google Chrome so that the user agent wont leak my model because there are so few people using this model.
But i dont actually want to affect other apps. I want to leave my model info unchanged when other apps read it.
Is there anyway to "whitelist"(bypass) all other apps or "blacklist" only Google Chrome?
Thanks

**Comment by Didgeridoohan** [comment]
No. Not with this tool. Prop changes using Magisk are global.
