### ISSUE TITLE
HTC U12+ Android Pie (9) fingerprint

### ISSUE THREAD

**Issue by jeanrivera** [Magisk-Modules-Repo/MagiskHidePropsConf#47]
Fingerprint	htc/imeuhl_00617/htc_imeuhl:9/PQ2A.190205.003/1087121.1:user/release-keys
 	 
Android	 
- Release	9
- SDK	28
- Security Patch	2019-07-01

**Comment by Didgeridoohan** [comment]
Print included in https://github.com/Magisk-Modules-Repo/MagiskHidePropsConf/commit/13a72e0f9603f42372341d8162159762cec68d40
