### ISSUE TITLE
Add new fingerprints

### ISSUE THREAD

**Issue by simonsmh** [Magisk-Modules-Repo/MagiskHidePropsConf#50]
Add:
```
Xiaomi Mi 10 (10):Xiaomi:Mi 10=Xiaomi/umi/umi:10/QKQ1.191117.002/V11.0.15.0.QJBCNXM:user/release-keys__2020-02-01
Xiaomi Mi 10 Pro (10):Xiaomi:Mi 10 Pro=Xiaomi/cmi/cmi:10/QKQ1.191117.002/V11.0.13.0.QJACNXM:user/release-keys__2020-02-01
```
Edit:
```
Xiaomi Mi Mix 2S (8.0.0 & 9 & 10):Xiaomi:Mi MIX 2S=Xiaomi/polaris/polaris:8.0.0/OPR1.170623.032/V9.5.19.0.ODGMIFA:user/release-keys;Xiaomi/polaris/polaris:9/PKQ1.180729.001/V10.3.3.0.PDGMIXM:user/release-keys__2019-05-01;Xiaomi/polaris/polaris:10/QKQ1.190828.002/V11.0.1.0.QDGCNXM:user/release-keys__2019-12-01
```

**Comment by Didgeridoohan** [comment]
Thanks. I'm pretty sure the 10 and 10 Pro security patch dates should be 2020-02-01 though. Right?

**Comment by simonsmh** [comment]
Yes, my mistake.

**Comment by Didgeridoohan** [comment]
Included in the new list update.

**Comment by ak414** [comment]
> Add:
> 
> ```
> Xiaomi Mi 10 (10):Xiaomi:Mi 10=Xiaomi/umi/umi:10/QKQ1.191117.002/V11.0.15.0.QJBCNXM:user/release-keys__2020-02-01
> Xiaomi Mi 10 Pro (10):Xiaomi:Mi 10 Pro=Xiaomi/cmi/cmi:10/QKQ1.191117.002/V11.0.13.0.QJACNXM:user/release-keys__2020-02-01
> ```
> 
> Edit:
> 
> ```
> Xiaomi Mi Mix 2S (8.0.0 & 9 & 10):Xiaomi:Mi MIX 2S=Xiaomi/polaris/polaris:8.0.0/OPR1.170623.032/V9.5.19.0.ODGMIFA:user/release-keys;Xiaomi/polaris/polaris:9/PKQ1.180729.001/V10.3.3.0.PDGMIXM:user/release-keys__2019-05-01;Xiaomi/polaris/polaris:10/QKQ1.190828.002/V11.0.1.0.QDGCNXM:user/release-keys__2019-12-01
> ```

where poco f1 miui 11 Android 10, custom rom is showing " ctsProfile false. please help bro

**Comment by Mohameds21** [comment]
Please add finger print for Xiaomi redmi note 8 pro Android 10  support

**Comment by Mohameds21** [comment]
Support Xiaomi redmi note 8 pro Android 10 please pro the cts profile flase and the basicintegrity also false help me please

**Comment by Didgeridoohan** [comment]
@Mohameds21 Take a look here:
https://github.com/Magisk-Modules-Repo/MagiskHidePropsConf/blob/master/README.md#please-add-support-for-device-x

But it sounds like you could first benefit from reading this:
https://www.didgeridoohan.com/magisk/MagiskHide#hn_SafetyNet

**Comment by Mohameds21** [comment]
Thanks pro 👍 all what i needed is to clear cache for Google play services and hell ya it works
