### ISSUE TITLE
It still doesn't work for Citibank CN

### ISSUE THREAD

**Issue by JF950908** [Magisk-Modules-Repo/MagiskHidePropsConf#54]
Hopefully, future versions will be supported.thanks

**Comment by Didgeridoohan** [comment]
This module doesn't do anything for specific apps. It's for passing SafetyNet CTS profile check and to set other prop values on your device.

If you have issues with MagiskHide and specific apps, take a look here:
https://didgeridoohan.com/magisk/MagiskHide#hn_Hiding_root_from_apps
