### ISSUE TITLE
S20 Ultra

### ISSUE THREAD

**Issue by wunerrahdev** [Magisk-Modules-Repo/MagiskHidePropsConf#55]
Hello please add fingerprint for S20 Ultra SM-G988B

Thank You

**Comment by Didgeridoohan** [comment]
Please provide one and I will.

https://github.com/Magisk-Modules-Repo/MagiskHidePropsConf/blob/master/README.md#please-add-support-for-device-x

**Comment by wunerrahdev** [comment]
samsung/z3sxxx/z3s:10/QP1A.190711.020/G988BXXU1ATCT:user/release-keys

**Comment by Didgeridoohan** [comment]
Thanks. If you could provide the security patch date for that print I can test it out.

**Comment by wunerrahdev** [comment]
April 1, 2020

**Comment by Didgeridoohan** [comment]
Print included in https://github.com/Magisk-Modules-Repo/MagiskHidePropsConf/commit/bae99da2ba5b08346bda52d162e08243734cea23
