### ISSUE TITLE
Add Poco F2 Pro (EEA) Fingerprint

### ISSUE THREAD

**Issue by RealAkito** [Magisk-Modules-Repo/MagiskHidePropsConf#57]
ro.vendor.build.fingerprint=POCO/lmi_eea/lmi:10/QKQ1.191117.002/V11.0.6.0.QJKEUXM:user/release-keys
ro.product.vendor.brand=POCO
ro.product.vendor.device=lmi
ro.product.vendor.model=POCO F2 Pro
ro.product.vendor.name=lmi_eea
ro.product.board=lmi
ro.bootimage.build.fingerprint=POCO/lmi_eea/lmi:10/QKQ1.191117.002/V11.0.6.0.QJKEUXM:user/release-keys

ro.vendor.build.security_patch=2020-04-01

**Comment by RealAkito** [comment]
Lemme grab Redmi K30 Pro Zoom Edition (CN Variant) fingerprint for you

**Comment by RealAkito** [comment]
Oh also, I think Pocophone F1 fingerprint is in the wrong category? It should be in POCO category like X2.

**Comment by RealAkito** [comment]
Redmi K30 Pro Zoom Edition [CN Variant]

ro.vendor.build.fingerprint=Redmi/lmipro/lmipro:10/QKQ1.191117.002/V11.0.16.0.QJKCNXM:user/release-keys
ro.product.vendor.brand=Redmi
ro.product.vendor.device=lmipro
ro.product.vendor.model=Redmi K30 Pro Zoom Edition
ro.product.vendor.name=lmipro
ro.product.board=lmipro
ro.bootimage.build.fingerprint=Redmi/lmipro/lmipro:10/QKQ1.191117.002/V11.0.16.0.QJKCNXM:user/release-keys

ro.vendor.build.security_patch=2020-04-01

**Comment by RealAkito** [comment]
Hi, I'll assume that's a okay from you by that emojis.

I'll close this now.

**Comment by Didgeridoohan** [comment]
Yes, the prints check out and I'm adding them to the next update (I'm working a bit on the code as well, and hopefully I can get some time to get things out there in the next couple of days).

**Comment by Didgeridoohan** [comment]
The prints have now been included in the latest update. Thanks again.

> Oh also, I think Pocophone F1 fingerprint is in the wrong category? It should be in POCO category like X2.

I forgot to reply to this... The manufacturer included in the Pocophone F1 print is Xiaomi, thus I categorise it as Xiaomi. Thanks for reminding me of relabelling a couple of Redmi prints I had previously labelled as Xiaomi though.

**Comment by RealAkito** [comment]
Lovely! Thanks.
