### ISSUE TITLE
cts profile false xiaomi note 8 pro android 10

### ISSUE THREAD

**Issue by Mohameds21** [Magisk-Modules-Repo/MagiskHidePropsConf#58]
hello i have an issue with the safetynet that i cannot pass the cts profile test i can pass the basic inegrity fine but cts  no and i am installing the module and using it of course and it was working fine on android 9 which is supported but after i have got the update of android 10 it does not work any more and i have tried alot off solution but there is no changes so please could you add support for   xiaomi redmi note 8 pro android 10 or explain to me how can i add my own and i will 
![Screenshot_2020-06-05-08-34-29-096_com PyFBukGZeu0 abGm](https://user-images.githubusercontent.com/66061661/83845099-87508700-a708-11ea-88bc-a9cd55dc416d.jpg)
![Screenshot_2020-06-05-08-34-51-535_jackpal androidterm](https://user-images.githubusercontent.com/66061661/83845103-89b2e100-a708-11ea-8793-263d30ec5203.jpg)
![Screenshot_2020-06-05-08-37-15-973_org freeandroidtools safetynettest](https://user-images.githubusercontent.com/66061661/83845108-8a4b7780-a708-11ea-91d0-e7680f699095.jpg)

**Comment by Didgeridoohan** [comment]
Start by taking a look in the docs:
https://github.com/Magisk-Modules-Repo/MagiskHide-Props-Config/blob/master/README.md#i-still-cant-pass-the-ctsprofile-check

And of course, regarding updating fingerprints available in the module:
https://github.com/Magisk-Modules-Repo/MagiskHidePropsConf/blob/master/README.md#please-update-fingerprint-x

There's no such thing as "adding support for" that or that version though. If your device doesn't pass with one of the certified fingerprints from the included list there's something else going on. More details on using different fingerprints here:
https://github.com/Magisk-Modules-Repo/MagiskHidePropsConf/blob/master/README.md#can-i-use-any-fingerprint
