### ISSUE TITLE
Magisk prop configuration v5.2.5

### ISSUE THREAD

**Issue by deathstroke6116** [Magisk-Modules-Repo/MagiskHidePropsConf#59]
It's worked fine .but after I updated to v5.2.6 CTS,,basic integrity show false.so changed it to v5 2.5.its also not working.cts is false.any solutions please.busy box is not installed on my phone.when version 5.2.5 was working ,I didn't installed busy box on my mobile

**Comment by Didgeridoohan** [comment]
Start by taking a look in the docs, here:
https://github.com/Magisk-Modules-Repo/MagiskHidePropsConf/blob/master/README.md#i-still-cant-pass-the-ctsprofile-check
