### ISSUE TITLE
service .d module script sh ran out 

### ISSUE THREAD

**Issue by silvi33** [Magisk-Modules-Repo/MagiskHidePropsConf#61]
![Screenshot_20200715-222334_Qute](https://user-images.githubusercontent.com/68015790/87660258-5ba5cf80-c791-11ea-967e-a4fd15709171.jpg)
![Screenshot_20200715-222238_Qute](https://user-images.githubusercontent.com/68015790/87660282-66f8fb00-c791-11ea-887a-d40178313863.jpg)
![Screenshot_20200715-235812_7Zipper](https://user-images.githubusercontent.com/68015790/87660296-6bbdaf00-c791-11ea-91cf-37f9cad9235c.jpg)

> please help !!

**Comment by Didgeridoohan** [comment]
I'll need the logs mentioned in the first screenshot. The propslogs.tar.gz file found on your internal storage.

**Comment by silvi33** [comment]
Sent from my Samsung Galaxy smartphone.
-------- Original message --------From: Didgeridoohan <notifications@github.com> Date: 16/07/2020  18:48  (GMT+08:00) To: Magisk-Modules-Repo/MagiskHidePropsConf <MagiskHidePropsConf@noreply.github.com> Cc: silvi <sammiteoh5932@gmail.com>, Author <author@noreply.github.com> Subject: Re: [Magisk-Modules-Repo/MagiskHidePropsConf] service .d module script sh ran out  (#61) 
I'll need the logs mentioned in the first screenshot. The propslogs.tar.gz file found on your internal storage.

**Comment by Didgeridoohan** [comment]
It looks like you posted that through email, so if you attached the file it did not come through. You'll need to visit the website and attach the file there.

**Comment by silvi33** [comment]
Ohh sorry then... I make it now ya..Sent from my Samsung Galaxy smartphone.
-------- Original message --------From: Didgeridoohan <notifications@github.com> Date: 16/07/2020  22:36  (GMT+08:00) To: Magisk-Modules-Repo/MagiskHidePropsConf <MagiskHidePropsConf@noreply.github.com> Cc: silvi <sammiteoh5932@gmail.com>, Author <author@noreply.github.com> Subject: Re: [Magisk-Modules-Repo/MagiskHidePropsConf] service .d module script sh ran out  (#61) 
It looks like you posted that through email, so if you attached the file it did not come through. You'll need to visit the website and attach the file there.

**Comment by silvi33** [comment]
[propslogs.tar.gz](https://github.com/Magisk-Modules-Repo/MagiskHidePropsConf/files/4932190/propslogs.tar.gz)

**Comment by Didgeridoohan** [comment]
The most likely suspect is the Cloudflare modules (they're known for breaking the Magisk boot process). Remove those and see if things start working.

And, I suggest that you don't add so many apps to the MagiskHide list. You should only add those few apps that actually detect root. Putting to many apps/services on the list may be detrimental for your system performance.

**Comment by silvi33** [comment]
![Screenshot_20200717-121413_Termux](https://user-images.githubusercontent.com/68015790/87763975-388a2700-c848-11ea-88b7-cb83f7bb852b.jpg)

**Comment by silvi33** [comment]
Finally get back....  thanks for info & help. Appreciate indeed.
