### ISSUE TITLE
Device simulation doesn't work.

### ISSUE THREAD

**Issue by quantmint** [Magisk-Modules-Repo/MagiskHidePropsConf#63]
I enabled coral fingerprint and device simulation with all props on, but from what i can see from SmartPack-Kernel Manager build prop section only ro.system.build.fingerprint gets changed, all the other props like ro.product.system.brand and ro.product.system.name are unchanged.
[propslogs.tar.gz](https://github.com/Magisk-Modules-Repo/MagiskHidePropsConf/files/5027041/propslogs.tar.gz)

**Comment by Didgeridoohan** [comment]
According to your log those props have all been changed as intended.

I'm assuming that the app you're using is looking at the actual build.prop file, I'm which case this part of the module docs are very relevant:
https://github.com/Magisk-Modules-Repo/MagiskHidePropsConf/blob/master/README.md#my-buildprop-doesnt-change-after-setting-a-custom-prop-or-removing-a-prop-value
