### ISSUE TITLE
Doesn't work with magisk module audio modification library

### ISSUE THREAD

**Issue by kot6230** [Magisk-Modules-Repo/MagiskHidePropsConf#64]
![Screenshot_2020-08-17-22-06-14-632_com termux](https://user-images.githubusercontent.com/60502974/90454258-5a065900-e0fb-11ea-81a3-8cbb00bd4703.jpg)

**Comment by Didgeridoohan** [comment]
That very likely means that AML is messing up the Magisk's boot stages. I can't really tell without the logs though...

Anyway, it's not actually an issue with this module. It's just showing the symptoms.

**Comment by kot6230** [comment]
#63
