### ISSUE TITLE
Attempting to install this module results in constant restarts within a minute of loading OS

### ISSUE THREAD

**Issue by rocket0634** [Magisk-Modules-Repo/MagiskHidePropsConf#66]
I have just installed cm13 over my Samsung Galaxy J3 today as I wanted access to Android 6.0.0 which was promised for the phone years ago and was never released.
I've previously became familiar with magisk when playing Pokemon GO on this device a year or so ago, and with the game losing support for Android 5 devices, I thought maybe I'd try getting it to work again using an old version of cm13 I found.
I ran the safetynet test and found that I did not pass the ctsProfile check, which makes sense as it's a custom rom and I had to wipe the system in order to install it.
So I installed Magisk Manager, Busybox, and this module to edit the props to see if I could fix the phone's fingerprint to be what it was before I wiped it, but immediately after installing this module and rebooting the phone, I find that after a minute of loading my phone, everything closes and the phone automatically reboots. I have enough time to open termux and run su/props before the reset takes place. Doing so gives me a "service.sh does not appear to have run during boot" error, which I suppose could suggest that trying to load service.sh is what causes the reboot.
Uninstalling the module returns the phone to working order.

**Comment by Didgeridoohan** [comment]
I'd need to at least see the module logs. Take a look here on how to get those: https://github.com/Magisk-Modules-Repo/MagiskHide-Props-Config/blob/master/README.md#logs

You could also try grabbing an ADB logcat when things start crashing.

And lastly, since the device is rebooting there might be some info in console-ramoops and/or last_kmsg as well.

Take a look here for more logging info; https://www.didgeridoohan.com/magisk/MagiskHelp

**Comment by rocket0634** [comment]
Apologies for that, I wasn't sure how to obtain the logs from my device, but I grabbed all I could based on the readme.

[propsconf-logs.zip](https://github.com/Magisk-Modules-Repo/MagiskHidePropsConf/files/5208566/propsconf-logs.zip)

**Comment by Didgeridoohan** [comment]
Thanks, I'll take a closer look when I have an opportunity. But, I can immediately say that it looks very weird, almost like you do not have superuser access during boot when the boot scripts are executed...

Could you actually try running a logcat boot script as described here (scroll down) and post the resulting log file: https://www.didgeridoohan.com/magisk/MagiskHelp

**Comment by rocket0634** [comment]
Using the given script and giving it 0777 permissions results in cyanogenmod crashing before making it to my home screen.
No boot.log can be found in the internal memory.

**Comment by Didgeridoohan** [comment]
I suspected that there

**Comment by Didgeridoohan** [comment]
I suspected there would be issues... D'oh!

Could you please update to the Canary releases. Partly to get better logs (Magisk log), but also to see if things work better on that build (there's been a lot of work on Magisk since v20.4).

**Comment by rocket0634** [comment]
I have gotten the canary manager since posting this issue but attempting to install the app generally fails. Should I try flashing through TWRP instead?

**Comment by Didgeridoohan** [comment]
Have you tried uninstalling the v7.5.1 app first?

Flashing in TWRP could work. Worth a shot... Make sure to save the recovery log after flashing, in case it shows anything interesting.

**Comment by rocket0634** [comment]
Flashing Magisk canary worked! However, now I'm incapable of installing modules. The zips are stated to not be magisk modules. Do I need to download modules specifically for canary?
[magisklog.zip](https://github.com/Magisk-Modules-Repo/MagiskHidePropsConf/files/5211390/magisklog.zip)

**Comment by Didgeridoohan** [comment]
That's weird... Do you get that message in the console window?

Could be that the repackaging of the zip isn't working properly. Could you try downloading the module zip directly from [here on GitHub](https://github.com/Magisk-Modules-Repo/MagiskHidePropsConf/releases/latest) and see if that works?

**Comment by rocket0634** [comment]
Yes, on the window that says "installation" it says
```
- Copying zip to temp directory
! This zip is not a Magisk Module!
! Installation failed
```
This same zip worked before installing canary and both this and busybox result in the same message.

**Comment by Didgeridoohan** [comment]
Do you get that message both when trying to install from the Manager Downloads as well as manually installing a zip downloaded from here?

**Comment by rocket0634** [comment]
That's correct

**Comment by Didgeridoohan** [comment]
Could you [record a logcat](https://www.didgeridoohan.com/magisk/MagiskHelp) when trying to install a module? Hopefully should show something...

**Comment by rocket0634** [comment]
Here you go, don't know if it's much help though

[logcat.txt](https://github.com/Magisk-Modules-Repo/MagiskHidePropsConf/files/5211515/logcat.txt)

**Comment by Didgeridoohan** [comment]
Doesn't look like there's anything in there, no...

I currently do not know what to do. I do not think it's a module specific issue though, but rather something about your device/ROM.

Thought: have you tried running that logcat boot script on the Canary install? Just to see if it works.

**Comment by rocket0634** [comment]
I can get past the home menu with canary now, but it still seems to like to reboot when I try using that logcat boot script.
Granted, the version of CM13 I'm using on my phone is an abandoned test build as it was the only one I could find for my model, so I'm not surprised with all of the issues that popped up. So I suppose it's something that I'll just have to deal with.

**Comment by Didgeridoohan** [comment]
Doesn't sound like there's much we can do... Sorry about that.
