### ISSUE TITLE
Pixel 4a simulation showing up as google sunfish

### ISSUE THREAD

**Issue by skadoosh99** [Magisk-Modules-Repo/MagiskHidePropsConf#68]
The pixel 4a simulation is not showing up properly in the module. After reboot, the device is being shown as "google pixel sunfish" and not google pixel 4a. How can we change this?

**Comment by Didgeridoohan** [comment]
I see it... There's a small typo somewhere when setting partition props, so the model value for system, vendor, odm and system_ext get set to just "Pixel". I'll take a closer look in a very near future.

**Comment by skadoosh99** [comment]
You actually replied 😂
LMAO! It's alright bruv...take your time.
Your service is really good
Hope you end up getting a great life.
And would you want me to send you SS of build prop or something? Please do
tell!

**Comment by skadoosh99** [comment]
Please do the needful. Could you let me know when it's done?

**Comment by Didgeridoohan** [comment]
I'm keeping this open until it's been fixed, so you'll know once I close it.

**Comment by Didgeridoohan** [comment]
Fixed in 1671e0c4e677981a7bb0f4c86d1a621970892900

**Comment by skadoosh99** [comment]
Problem still persists

**Comment by Didgeridoohan** [comment]
It shouldn't, but you might have to reapply the fingerprint to force a refresh of the system.prop file.

**Comment by skadoosh99** [comment]
I tried 3/4 times and still it does the same, it's being shown as google
sunfish.

**Comment by Didgeridoohan** [comment]
Of you've still got issues I'm going to have to see the module logs.

https://github.com/Magisk-Modules-Repo/MagiskHide-Props-Config/blob/master/README.md#logs

**Comment by skadoosh99** [comment]
How should I send you that?

**Comment by Didgeridoohan** [comment]
Attach the log file here in the issue.

**Comment by skadoosh99** [comment]
Is this it?

**Comment by skadoosh99** [comment]
This?

**Comment by Didgeridoohan** [comment]
There's nothing attached to that post. If you're replying through email, you have to visit the website to be able to attach a file.

**Comment by skadoosh99** [comment]
How to upload file?

**Comment by Didgeridoohan** [comment]
https://docs.github.com/en/github/managing-your-work-on-github/file-attachments-on-issues-and-pull-requests

**Comment by skadoosh99** [comment]
Bruh, I'm using phone,so unable to do this. Could you give any other place
where I can upload this?
Coz this is a .tar file

**Comment by Didgeridoohan** [comment]
Ever heard of "Desktop view" in mobile browsers? You could also just post a link to your cloud/sharing service of choice.

**Comment by skadoosh99** [comment]
Bro...I tried this is 3 different roms, in everything this is the scenario.
Even one of my friends got the same results.
So doesn't that mean the module is faulty??

**Comment by Didgeridoohan** [comment]
> Bro...I tried this is 3 different roms, in everything this is the scenario. Even one of my friends got the same results. So doesn't that mean the module is faulty??

Yes, that's very possible. But without those logs it's really hard for me to tell (let alone fix if it is broken).

**Comment by skadoosh99** [comment]
https://drive.google.com/file/d/1-t8Fvxo-3Zg_F0El5wN1Cqmlu8eF8oAE/view?usp=drivesdk

**Comment by Didgeridoohan** [comment]
Thank you.

Although, everything looks exactly as it should... I can't see anything wrong. When you say that you see that the device is a "Pixel sunfish", were do you see this? There's no "sunfish" anywhere on your device, according to those logs (which isn't surprising really, since you're simulating a "bonito", 3a XL).

Again, were do you see it reporting the wrong props?

**Comment by skadoosh99** [comment]
In my gmail login and in an app called "my device" which shows device information.

**Comment by Didgeridoohan** [comment]
> In my gmail login
That's probably been cached by Google. Nothing I can do about that...

> and in an app called "my device" which shows device information.
Link to the app? Screenshot? Help me help you...

As far as I can see, from the logs you provided, the module works exactly as it should now.

**Comment by skadoosh99** [comment]
Then what could be the problem in your opinion??

**Comment by Didgeridoohan** [comment]
> Then what could be the problem in your opinion??

Like I said, with Google it's likely an issue with them caching a previous device check.

With the app, I don't know since I don't know exactly which app you're talking about (there are tons of "My device" apps). A link or at least a screenshot would help. It's not checking prop, it seems...

**Comment by skadoosh99** [comment]
https://drive.google.com/file/d/10RGzA4jchpWQWC9x-QWbm--5zOiyv3gf/view?usp=drivesdk

Hope this helps

**Comment by Didgeridoohan** [comment]
As far as I can tell there's nothing wrong. Unless you did not have the Pixel 4a set for simulation when taking that screenshot.

That app simply shows the device name rather than the model for the 4a...

**Comment by skadoosh99** [comment]
I don't know bruh, when I tried other simulation,it would show the name.
I tried other pixel devices 2xl, 3xl etc
For everything name was shown as "pixel 2xl/3xl" etc

**Comment by Didgeridoohan** [comment]
> I don't know bruh, when I tried other simulation,it would show the name. I tried other pixel devices 2xl, 3xl etc For everything name was shown as "pixel 2xl/3xl" etc

I know, I've tested the app. But from what I can see, the props get set as they should (you can even see this in the other pages of the app). And technically, it's not wrong... The device model is "Pixel 4a" and the device name is "sunfish". 

Unless you can show otherwise (there might of course be something I've missed), I'm writing this down as a quirk of that particular app. Case closed.

**Comment by skadoosh99** [comment]
Hmm...I guess that's that. Sorry for wasting your time bruv!
Thanks for fast replies! Really appreciate it!

**Comment by Didgeridoohan** [comment]
> Hmm...I guess that's that. Sorry for wasting your time bruv! Thanks for fast replies! Really appreciate it!

No time was wasted. There was indeed a bug that you helped me find. Thanks for that.

**Comment by skadoosh99** [comment]
No mention bruv!

**Comment by skadoosh99** [comment]
Hey bro, so I get someone who owns the pixel 4a to send their build prop.
Hope this helps.
https://drive.google.com/file/d/1-vNy7hy7Q3fJmAguTlPDnWr54z9TkzR1/view?usp=drivesdk

**Comment by Didgeridoohan** [comment]
You need to turn on link sharing if I'm going to be able to download that.

**Comment by skadoosh99** [comment]
Sorry for that, it's turned on now!
