### ISSUE TITLE
Still an issue.

### ISSUE THREAD

**Issue by enezzolation** [Magisk-Modules-Repo/MagiskHidePropsConf#76]
![Screenshot_20201110-201219_Root Essentials](https://user-images.githubusercontent.com/67480892/98707503-2b61ec80-2391-11eb-9b3f-a7acff801800.jpg)

Even though I reset my fingerprint,it is still shown as Google Pixel 4 XL. I think I attached a file,not sure if it is uploaded tho. If you can see it,you can see that I have an Exynos chipset. None of Google phones use Exynos.

**Comment by Didgeridoohan** [comment]
You can always try using the full reset option in the main menu (and don't forget to reboot).

There was no attachment, but if you need further help I do need to see the module logs...

**Comment by enezzolation** [comment]
Still having the issue. I am still not sure if I attached the logs but it should be here: 
[Uploading propslogs.tar.gz…]()

**Comment by enezzolation** [comment]
Sorry. I am a GitHub newbie. I uploaded the logs to Google Drive. Thanks. 


https://drive.google.com/file/d/18Dnz2HPRZ6lkC5c41q4ioN0wqiy0S214/view?usp=drivesdk

**Comment by Didgeridoohan** [comment]
Those logs show that the module has been completely reset and there's nothing that it could do to set the Pixel 4 XL props.

But, looking at your Magisk log I'm slightly suspicious of the module named "Coral-Props" (coral = Pixel 4 XL)...

Are you sure that it's this module that's causing your problem?

**Comment by enezzolation** [comment]
OMFG! THANKS FOR YOUR HELP!!!! It was that module. I cannot thank you enough. You are the BEST!!!
