### ISSUE TITLE
Force "Basic" attestion issue for some selected device names

### ISSUE THREAD

**Issue by Micdu70** [Magisk-Modules-Repo/MagiskHidePropsConf#77]
Hello there,

Force "Basic" attestion doesn't work if you chose "Mi 10 Europe" or "Mi 10 China" as device model name. Reason is that it will rename the device as "Mi 10" so it's useless and it can't work. :(

Proposal: Renaming device model name as "Mi 10 Europe" or "Mi 10 China". It should be fine. :)

**Comment by Didgeridoohan** [comment]
Hi.

That would be a: nope.

The actual model name for those devices are "Mi 10", and therefore that's what I'll be using in the module list. If you want to use "Europe" or "China" in the model name you are welcome to use the "Custom value" option.
