### ISSUE TITLE
Add support for SM-A705FN variant

### ISSUE THREAD

**Issue by phennaux** [Magisk-Modules-Repo/MagiskHidePropsConf#78]
Hi could you please add support for the _Samsung Galaxy A70 (FN variant)_ ?

Here's the fingerprint and security patch:

Fingerprint: 
samsung/a70qxx/a70q:10/QP1A.190711.020/A705FNXXU5CTK4:user/release-keys

Security patch:
ro.build.version.security_patch=2020-11-01

**Comment by Didgeridoohan** [comment]
Forgot to close this... Added in https://github.com/Magisk-Modules-Repo/MagiskHidePropsConf/commit/36cdf6a855aa2bd854bfc2efccd5c8434c731ab4#diff-92a5dc04bd6f9fb8f29f8066fed8a5c1e81bc59ad48a11283b63736867e4f2a8
