### ISSUE TITLE
Add Xiaomi9 new fingerprint

### ISSUE THREAD

**Issue by Mr54233** [Magisk-Modules-Repo/MagiskHidePropsConf#79]
Android 11 

Xiaomi 
MI 9 
Xiaomi/cepheus/cepheus:11/RKQ1.200826.002/20.12.28:user/release-keys

Do I need more information for the first submission?

thank u

**Comment by Didgeridoohan** [comment]
The security patch date is also necessary to be able to pass CTS.

**Comment by Mr54233** [comment]
ok the date is the 2020-12-01

**Comment by Didgeridoohan** [comment]
Unfortunately this print fails CTS, and even causes basic integrity to fail on my test device.
