### ISSUE TITLE
meizu 17 (Android 10) pass CTS

### ISSUE THREAD

**Issue by sh3rry** [Magisk-Modules-Repo/MagiskHidePropsConf#80]
[build.prop](https://0bin.net/paste/N7jHv9CD#0zbWZyOzpbzR3L81OWPUhDcgm5l-Z4clAsEWczzxC7B)

**Comment by sh3rry** [comment]
meizu 17 (10):meizu:meizu 17=meizu/meizu_17_N_CN/meizu17:10/QKQ1.200223.002/1599445800:user/release-keys__2020-07-01

**Comment by Didgeridoohan** [comment]
Added in https://github.com/Magisk-Modules-Repo/MagiskHidePropsConf/commit/a548a8dc2f4424481080822ac825c7bdfb25de64
