### ISSUE TITLE
Redmi 8 (Android 10) CTS Fail Hardware

### ISSUE THREAD

**Issue by poqdavid** [Magisk-Modules-Repo/MagiskHidePropsConf#81]
I have been trying to get the cts profile to pass so I had to go with "force basic key attestation" but I can't find my device in the list there is only china version the only way that it works is that I pick Redmi Note 8 Pro
I was wondering if it's possible to add Redmi 8 Global to the list so the device model doesn't change to something else I would appreciate it

**Comment by Didgeridoohan** [comment]
The only way to fool SafetyNet into using the basic attestation is to use a different model from your own... No way around it (currently).
