### ISSUE TITLE
newest fingerprint for k20pro（stable android 10）

### ISSUE THREAD

**Issue by liwenjie119** [Magisk-Modules-Repo/MagiskHidePropsConf#82]
Xiaomi Redmi K20 Pro (10)=Xiaomi/raphael/raphael:10/QKQ1.190825.002/V12.0.6.0.QFKCNXM:user/release-keys__2020-11-01

Android 11 MIUI12.5 stable is not release

**Comment by Didgeridoohan** [comment]
Added in https://github.com/Magisk-Modules-Repo/MagiskHidePropsConf/commit/a548a8dc2f4424481080822ac825c7bdfb25de64
