### ISSUE TITLE
Basic key attestation gone

### ISSUE THREAD

**Issue by jojos38** [Magisk-Modules-Repo/MagiskHidePropsConf#83]
Hi, since the latest update I can't find Basic key attestation thing, I have no idea what that is and what it does but it was the only option that allowed my phone to pass safetynet. Is there any way to bring it back please?

**Comment by Didgeridoohan** [comment]
If your read the changelog for v5.4.0, and also the documentation on this feature, you'll see that this trick no longer works and you'll have to use another method (that is linked in both the changelog and docs).
