### ISSUE TITLE
Fingerprint sensor issue

### ISSUE THREAD

**Issue by david-lev** [Magisk-Modules-Repo/MagiskHidePropsConf#84]
Hi, after I changed the fingerprint of the device through the module, all the applications that support authentication via the fingerprint sensor - no longer work unless they use Samsung's fingerprint window.
Is there a chance it is related?  Even after I reset my fingerprint the problem still remained.
What apps are these? Lastpass, TickTick, banks and more.

I'm using Samsung Galaxy S9+![20210120_105037.jpg](https://user-images.githubusercontent.com/42866208/105150355-585b1a00-5b0d-11eb-8989-28481067dd85.jpg)

**Comment by Didgeridoohan** [comment]
It can of course be related to the fingerprint change, if that's all you did before this problem manifested.

But, I'll start by asking if you also installed the new Universal SafetyNet Fix when you changed the device fingerprint? That module edits the keystore on your device and is known to sometimes cause problems with fingerprint authentication.

**Comment by david-lev** [comment]
You're right, I also installed that SafetyNet module.  If I remove it, will it help?

**Comment by Didgeridoohan** [comment]
It will most likely help with your fingerprint issue, but you are unlikely to be able to pass CTS.

Closing this, since it's not related to this module. Please feel free to continue posting though, if you need further assistance...
