### ISSUE TITLE
ADD FINGERPRINT FOR REDMI NOTE 9 PRO MAX (INDIA/GLOBAL)

### ISSUE THREAD

**Issue by DevRiturajKumar** [Magisk-Modules-Repo/MagiskHidePropsConf#89]
THERE IS NO DEVICE FINGERPRINT FOR REDMI NOTE 9 PRO MAX, PLEASE ADD FOR REDMI NOTE 9 PRO MAX (6GB/128GB). 👍👍
![Screenshot_2021-02-22-02-15-44-215_com termux](https://user-images.githubusercontent.com/30962769/108638180-ec752400-74b3-11eb-9742-4772d275eff9.jpg)

**Comment by Didgeridoohan** [comment]
Would love to:
https://github.com/Magisk-Modules-Repo/MagiskHidePropsConf/blob/master/README.md#please-add-support-for-device-x

**Comment by DevRiturajKumar** [comment]
Redmi/excalibur_in/excalibur:10/QKQ1.191215.002/V12.0.3.0.QJXINXM:user/release-keys

**Comment by DevRiturajKumar** [comment]
add the above fingerprint of redmi note 9 pro max

**Comment by DevRiturajKumar** [comment]
![Uploading Screenshot_2021-03-10-12-43-07-488_com.finalwire.aida64.jpg…]()

**Comment by DevRiturajKumar** [comment]
![Screenshot_2021-03-10-12-43-07-488_com finalwire aida64](https://user-images.githubusercontent.com/30962769/110595134-abfbf280-81a3-11eb-9d3f-14e19ae2a666.jpg)

**Comment by DevRiturajKumar** [comment]
![IMG_20210310_132349_072](https://user-images.githubusercontent.com/30962769/110595306-dfd71800-81a3-11eb-8a01-e7811d78bc0b.jpg)

**Comment by Didgeridoohan** [comment]
That passes CTS, thanks. I'll reopen this until I've added it to the prints list.

**Comment by DevRiturajKumar** [comment]
THIS SHOULD FIX THE "MONEY APPS", HOPING SO, PLEASE PUSH IT ASAP!

**Comment by Didgeridoohan** [comment]
If you're in such a hurry you can start using the print without it being on the included list...

Just enter the print manually in the "Edit device fingerprint" menu, or use a custom prints list:
https://github.com/Magisk-Modules-Repo/MagiskHide-Props-Config/blob/master/README.md#custom-fingerprints-list

There's no need to scream at me...

**Comment by DevRiturajKumar** [comment]
ohh, thanks for the reminder, fixed 👍

**Comment by Didgeridoohan** [comment]
Added in https://github.com/Magisk-Modules-Repo/MagiskHidePropsConf/commit/d908ed89ba9b429f9d086d8fc97e4cf9a7464fcf
