### ISSUE TITLE
Please add support for Xiaomi Redmi 9

### ISSUE THREAD

**Issue by marat2509** [Magisk-Modules-Repo/MagiskHidePropsConf#90]
Hello to the respected developers of Magisk Hide Props Config. I immediately apologize for writing here, not on Xda-Developers (since I have trouble entering). 
Thank you for understanding! 

Manufacturer: **Xiaomi**
Device: **Redmi 9**
Codename(s): **lancelot** (without NFC); **galahad** (with NFC)
Security Patch date: **2020.11.01**
AndroidDump (galahad): https://git.rip/dumps/redmi/galahad
Model(s): **M2004J19AG** and **M2004J19PI** - without NFC; **M2004J19C** - with NFC

Props:
**ro.product.model** (galahad, NFC)- M2004J19C
**ro.product.manufacturer** - Xiaomi
**ro.build.fingerprint** - Redmi/galahad_id/galahad:10/QP1A.190711.020/V12.0.1.0.QJCIDXM:user/release-keys

**Thank you in advance!**

**Comment by Didgeridoohan** [comment]
No worries, submitting prints here works great as well.

I've tested and I managed to get a print from that Android Dumps link to pass CTS. Not the one you've submitted here though...

Will add that one to the list in the next update.

**Comment by marat2509** [comment]
Thank you, and tell me when you plan an update?

**Comment by Didgeridoohan** [comment]
Added in 309dcf9e2ba6b93df256269654cfd01fba76f456
