### ISSUE TITLE
please add fingerprint for Samsung Galaxy  Tab 7 plus(T970),Thanks!!!!

### ISSUE THREAD

**Issue by a5782033** [Magisk-Modules-Repo/MagiskHidePropsConf#91]
![Screenshot_20210313-191914_DevCheck](https://user-images.githubusercontent.com/75343874/111028341-03fb5900-8431-11eb-87b4-e42c7f5e52ec.jpg)
![Screenshot_20210313-191948_DevCheck](https://user-images.githubusercontent.com/75343874/111028356-170e2900-8431-11eb-9e0b-709361311225.jpg)

When submitting a device fingerprint for inclusion in the module list, please provide the device name and the values from the following props:
- ro.build.fingerprint (but preferably all of the fingerprint props available on your device, since they don't always match)
- ro.build.version.security_patch
- ro.product.manufacturer
- ro.product.model

A simple way of getting all the required information is to use [ipdev's](https://github.com/ipdev99) great props extraction tool: https://github.com/ipdev99/mHideGP

**Comment by Didgeridoohan** [comment]
Added in https://github.com/Magisk-Modules-Repo/MagiskHidePropsConf/commit/d908ed89ba9b429f9d086d8fc97e4cf9a7464fcf
