### ISSUE TITLE
Service.sh not load

### ISSUE THREAD

**Issue by Gogo791** [Magisk-Modules-Repo/MagiskHidePropsConf#92]
![Screenshot_2021-03-22-00-24-47-343_in co pricealert apps2sd](https://user-images.githubusercontent.com/81108560/111916337-fc7d2500-8aac-11eb-904b-583785ebff61.jpg)
Help me in redmi 6a ubl, miui11, android9, twrp&magisk22.0

**Comment by Didgeridoohan** [comment]
If you read the message you've screenshoted, there are instructions to post logs (assuming that you've already tried everything else that's written there), and that they've been saved to your internal storage.

I can't do much helping without those logs...

**Comment by Gogo791** [comment]
> If you read the message you've screenshoted, there are instructions to post logs (assuming that you've already tried everything else that's written there), and that they've been saved to your internal storage.
> 
> I can't do much helping without those logs...

This is the logs file : https://ufile.io/zbrf5p8c

**Comment by Didgeridoohan** [comment]
Looks like the culprit is EdXposed, which also is mentioned as a possibility in the error message...

Make sure you've got the latest update to EdXposed.

**Comment by stroks15** [comment]
https://github.com/Magisk-Modules-Repo/MagiskHidePropsConf/blob/master/service.sh
