### ISSUE TITLE
Doesn't work on an emulator

### ISSUE THREAD

**Issue by phuongnd08** [Magisk-Modules-Repo/MagiskHidePropsConf#96]
I installed Magisk and MagisHidePropsConf on an emulator running android 11. Despite using basic evalType, it still fails both basicIntegrity and ctsProfile

What I did:
Choose  `1 - Edit device fingerprint (active)`
Choose `f - Pick a certified fingerprint`
Choose `7 - Google`
Choose `26 - Google Pixel 5 (11)`

Here is the output post setting:

```
 # resetprop ro.system.build.fingerprint
google/redfin/redfin:11/RRQ2A.210505.003/7255357:user/release-keys
```

The SafetyNet check output from Magisk Manager:

![image](https://user-images.githubusercontent.com/184037/117534476-d3dcca80-b01b-11eb-91ae-b5aa54720a3c.png)

**Comment by phuongnd08** [comment]
Also I go ahead and enable all simulation:

```
 s - Device simulation (enabled)
 1 - ro.product.brand (enabled)
 2 - ro.product.name (enabled)
 3 - ro.product.device (enabled)
 4 - ro.build.version.release (enabled)
 5 - ro.build.id (enabled)
 6 - ro.build.version.incremental (enabled)
 7 - ro.build.version.sdk (enabled)
 8 - ro.build.display.id (enabled)
 9 - ro.product.manufacturer (enabled)
10 - ro.product.model (enabled)
 a - Enable/disable all props
 d - ro.build.description (enabled)
 p - Use partition props (enabled)
 t - Boot stage (default)
 b - Go back
 e - Exit
```

But attestation still fails on both basicIntegrity and ctsProfile

**Comment by Didgeridoohan** [comment]
The SafetyNet API specifically checks for and fails both checks on an emulator. That's not something you can circumvent by using a certified device fingerprint.

This is not something I can help with or that has anything to do with the module. You'd have to do you own research into exactly what is detected.
