### ISSUE TITLE
I wont call it an issue because ur module is prefect 

### ISSUE THREAD

**Issue by qtr1st** [Magisk-Modules-Repo/MagiskHidePropsConf#98]
Would appreciate if u add rog 5 fingerprints values as per below
Asus ROG Phone 5 ZS673KS (10):Asus:ZS673KS=asus/WW_I005D/ASUS_I005_1:11/RKQ1.201022.002/18.0840.2103.26-0:user/release-keys__2021-03-05

Many thanks

**Comment by Didgeridoohan** [comment]
Added in 4c90e77ded3440c6bc3391cb4da5994a72f73a30

**Comment by AbandonedCart** [comment]
Asus ROG Phone 5 ZS673KS (10):Asus:ZS673KS=asus/WW_I005D/ASUS_I005_1:11/RKQ1.201022.002/18.0840.2104.49-0:user/release-keys__2021-04-05
