### ISSUE TITLE
build.prop list

### ISSUE THREAD

**Issue by slaiddominio** [Magisk-Modules-Repo/MagiskHidePropsConf#99]
Hello friend, where is the list with build.props, I wanted to download and use this list in a project.
It would be possible?

**Comment by Didgeridoohan** [comment]
There is no list of build.prop values. The only list you'll find here is the list of certified device fingerprints (in the /common directory).

**Comment by slaiddominio** [comment]
@Didgeridoohan Thank you very much, colleague.
